# In Silico Framework
# Copyright (C) 2025  Max Planck Institute for Neurobiology of Behavior - CAESAR
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Convert a :ref:`con_file_format` file to a dataframe with the number of connected presynaptic cells for each celltype and column."""

import os
import pandas as pd
from .reader import read_celltype_numbers_spreadsheet
from config.user.network_connectivity import DATA_REQS_UDVARY2022


def con_file_to_NumberOfConnectedCells_sheet(con_file, write_output=True):
    """Convert a :ref:`con_file_format` file to a dataframe with the number of connected presynaptic cells for each celltype and column.

    The dataframe has the following columns:

    - Presynaptic column: The column of the presynaptic cell.
    - Presynaptic cell type: The celltype of the presynaptic cell.
    - Connected presynaptic cells: The number of connected presynaptic cells.

    Args:
        con_file (str): path to :ref:`con_file_format` file generated by :class:`~singlecell_input_mapper.single_cell_input_mapper.network_embedding.NetworkMapper`
        write_output (bool):
            If True, the output is saved as a .csv file in the same folder as the con_file.
            If False, the output is returned as a pandas DataFrame.

    Warning:
        This method is specific to the barrel cortex, as it assumes the presence of columns.

    Returns:
        pandas.DataFrame | str: The dataframe, or the path to the .csv file if :param:`write_output` is True.

    """
    # read in .con_file
    con_pdf = pd.read_csv(
        con_file, sep="\t", skiprows=3, names=["type", "cell_ID", "synapse_ID"]
    )
    assert len(con_pdf) > 0, "The .con file is empty: {}".format(con_file)
    # groupb by celltype
    con_pdf = (
        con_pdf.groupby("type")
        .apply(lambda x: len(x.cell_ID.drop_duplicates()))
        .to_frame(name="Connected presynaptic cells")
        .reset_index()
    )
    # split type column in celltype and column
    con_pdf["Presynaptic cell type"] = con_pdf.apply(
        lambda x: x.type.split("_")[0], axis=1
    )
    con_pdf["Presynaptic column"] = con_pdf.apply(
        lambda x: x.type.split("_")[1], axis=1
    )
    # cell-column combinations that do not contain a single cell do not appear at this point in the table
    # add entries for such cell populations
    nr_cells = read_celltype_numbers_spreadsheet(DATA_REQS_UDVARY2022['numberOfCellsSpreadsheetName'])
    presynaptic_cell_types = {ct for v in nr_cells.values() for ct in v} 
    for anatomical_area in nr_cells:
        c_selected_pdf = con_pdf[con_pdf["Presynaptic column"] == anatomical_area]
        for cell_type in presynaptic_cell_types:
            if len(c_selected_pdf[c_selected_pdf["Presynaptic cell type"] == cell_type]) == 0:
                con_pdf = con_pdf.append(
                    pd.DataFrame(
                        {
                            "Presynaptic column": [anatomical_area],
                            "Presynaptic cell type": [cell_type],
                            "Connected presynaptic cells": [0],
                        }
                    )
                )
    # sort and select data
    con_pdf = con_pdf.sort_values("Presynaptic column")
    con_pdf = con_pdf[
        ["Presynaptic column", "Presynaptic cell type", "Connected presynaptic cells"]
    ]
    if write_output == False:
        return con_pdf
    # save in same folder as the .con file
    outpath = os.path.join(os.path.dirname(con_file), "NumberOfConnectedCells.csv")
    con_pdf.sort_values("Presynaptic column").to_csv(outpath, sep="\t", index=False)
    return outpath