import os, dask, glob
import numpy as np
import pandas as pd
import dask.dataframe as dd
from config.isf_logging import logger
from data_base.utils import chunkIt, unique

DEFAULT_VT_PARTITION_SIZE = 500
"Partition size to use for voltage trace dataframes if repartition is simply set to ``True``, without specifying a length."

@dask.delayed
def read_voltage_traces_from_files_pandas(prefix, fnames, meta=None):
    """Reads a list of **multiple** voltage trace files and parses it to a single pandas dataframe.

    The delayed version of this method is used to construct a dask dataframe containing the voltage traces
    in :py:meth:`~data_base.db_initializers.load_simrun_general.read_voltage_traces_by_filenames`.
    Each singular file is read using :py:meth:`~data_base.db_initializers.load_simrun_general.read_voltage_traces_from_file`.

    Args:
        prefix (str): Path to the directory containing the simulation results.
        fnames (list): List of filenames pointing to voltage trace files.

    Returns:
        pandas.DataFrame: A pandas dataframe containing the voltage traces.

    See also:
        :py:meth:`~data_base.db_initializers.load_simrun_general.read_voltage_traces_by_filenames`.
    """
    dfs = [read_voltage_traces_from_file(prefix, fname, meta=meta) for fname in fnames]
    return pd.concat(dfs, axis=0)


def read_voltage_traces_from_file(prefix, fname, meta=None):
    """Reads a **single** voltage traces file as generated by the simrun package.

    Infers the data format of the voltage traces file from the file extension (either ``.csv`` or ``.npz``).
    Reads them in and parses it to a pandas datafram, containing the original path and simulation trial as an index.

    Example:

        >>> simrun_result_fn = 'path/to/sim_result/vm_all_traces.csv'
        >>> with open(simrun_result_fn, 'r') as file: print(file.read())
        # This is an example for a .csv file (so not .npz)
        t	    Vm run 00	    Vm run 01
        100.0	-61.4607218758	-55.1366909604
        100.025	-61.4665809176	-55.1294343391
        100.05	-61.4735021526	-55.1223216173
        ...
        >>> read_voltage_traces_from_file(prefix="path/to/sim_result", v_fn)
        sim_trial_index             100.0           100.025         ...
        path/to/sim_result/000000   -61.4607218758 -61.4665809176   ...
        path/to/sim_result/000001   -55.1366909604 -55.1294343391   ...
        ...

    Important:
        The simulation trial index is inferred from the filename of the voltage traces file.
        Ideally, this path should contain a unique identifier, containing e.g. the date,
        seed and/or the PID of the simulation run.

    Args:
        prefix (str): Path to the directory containing the simulation results.
        fname (str): Filename pointing to a voltage trace file. The file can be in either ``.csv`` or ``.npz`` format.

    Returns:
        pd.DataFrame: A pandas dataframe containing the voltage traces.

    See also:
        :py:meth:`~data_base.db_initializers.load_simrun_general.read_voltage_traces_from_csv` and
        :py:meth:`~data_base.db_initializers.load_simrun_general.read_voltage_traces_from_npz`
    """
    logger.debug(f"Reading voltage trace file: {fname}")
    try:
        if fname.endswith(".csv"): return read_voltage_traces_from_csv(prefix, fname)
        if fname.endswith(".npz"): return read_voltage_traces_from_npz(prefix, fname)
    except Exception as e:
        logger.error(e)
        # Return empty DataFrame with same structure as meta
        # These will simply be ignored by upstream dd.from_delayed()
        empty_df = pd.DataFrame(columns=meta.columns).astype(meta.dtypes)
        return empty_df


read_voltage_traces_from_file_delayed = dask.delayed(read_voltage_traces_from_file)


def _get_sim_trial_index_from_simresult_dir(prefix, dir_path, check_n_traces=None):

    syn_files = [os.path.basename(f) for f in glob.glob(os.path.join(prefix, dir_path, "*synapses*"))]
    cell_files = [os.path.basename(f) for f in glob.glob(os.path.join(prefix, dir_path, "*presynaptic_cells*"))]

    if check_n_traces is not None:
        if not len(syn_files) == check_n_traces == len(cell_files): raise ValueError(
            "Amount of runs does not match: {} synapse activation files, {} voltage traces, and {} cell activation files".format(
                len(syn_files), check_n_traces, len(cell_files)))
    
    # Special case: if the simulations runs are not consecutive. Fetch the run id form the synapse activation files instead
    run_ids = sorted(int(f.split("_")[1][3:]) for f in syn_files)
    index = [
        str(os.path.join(dir_path, str(run_id).zfill(6)))
        for run_id in run_ids
    ] 
    return index


def read_voltage_traces_from_csv(prefix, fname):
    """Reads a single :ref:`voltage_traces_csv_format` file as generated by the simrun package.
    
    Attention:
        This function assumes that the data in :paramref:prefix: is complete, e.g. no missing files.
        It infers the simulation trial index from the filename of the synapse activation files.
        :py:fun:`_check_if_results_are_corrupted` checks if this is the case.
        This is automatically done in the :py:mod:`data_base.db_initializers.load_simrun_general` module.
        
    Args:
        prefix (str): Path to the directory containing the simulation results.
        fname (str): Filename pointing to a voltage trace file. The file is expected to be in ``.csv`` format.
        
    """
    full_fname = os.path.join(prefix, fname)

    df = pd.read_csv(
        full_fname, 
        sep=r"\t", # use tab as sep (not whitespace, the columntitles have spaces in them...)
        engine="python", # use python engine to handle whitespace
        dtype=np.float64, # ensure all data is read as float64
        )
    t = df.iloc[:, 0].to_numpy()        # first column = time
    data = df.iloc[:, 1:].to_numpy().T  # transpose: rows=traces, columns=time
    n_traces = data.shape[0]

    # special case: if only one row is contained in data, this has to be a column vector
    data = np.atleast_2d(data)

    # Construct the sim trial index for these voltage traces
    dir_path = os.path.dirname(fname)
    index = _get_sim_trial_index_from_simresult_dir(prefix, dir_path, check_n_traces=n_traces)
    
    result = pd.DataFrame(
        data, 
        columns=t, 
        index=index
        )
    result.index.name = "sim_trial_index"
    return result


# def read_voltage_traces_from_csv(prefix, fname):
#     """Reads a single :ref:`voltage_traces_csv_format` file as generated by the :py:mod:`simrun` package.

#     Args:
#         prefix (str): Path to the directory containing the simulation results.
#         fname (str): Filename pointing to a voltage trace file. The file is expected to be in ``.csv`` format.

#     See also:
#         :py:meth:`~data_base.db_initializers.load_simrun_general.read_voltage_traces_from_file`

#     Returns:
#         pd.DataFrame: A pandas dataframe containing the voltage traces.
#     """
#     full_fname = os.path.join(prefix, fname)
#     with open(full_fname) as f:
#         data = np.loadtxt(f, skiprows=1, unpack=True, dtype="float64")
#     # special case: if only one row is contained in data, this has to be a column vector
#     if len(data.shape) == 1:
#         data = data.reshape(len(data), 1)
#     t = data[0]
#     data = data[1:]
#     # In case the simulation trial indices are not consecutive
#     # TODO: ideally, these should not require checking synapse activation files. We had issues where corrupted data (with less syn act files than voltage trace columns)
#     # TODO: caused weird failures, as the index lenght did not match vt length.
#     # TODO: Changing this incurs a significant refactor though.
#     indices = sorted(
#         [
#             int(f.split("_")[1][3:])
#             for f in os.listdir(os.path.dirname(full_fname))
#             if "synapses" in f
#         ]
#     )
#     index = [
#         str(os.path.join(os.path.dirname(fname), str(index).zfill(6)))
#         for index in indices
#     ]  ##this will be the sim_trail_indexndex = [
#     # print index
#     df = pd.dataframe(data, columns=t)
#     if not data.shape[0] == len(index):
#         raise ValueError(
#             "found {} voltage traces in the voltage trace .csv: {}\n found a different amount of synapse activation .csvs: {}\ndata location: {}\n".format(
#                 data.shape[0], full_fname, len(index), os.path.dirname(full_fname))
#             )
#     df["sim_trial_index"] = index
#     df.set_index("sim_trial_index", inplace=True)
#     return df


def read_voltage_traces_from_npz(prefix, fname):
    """Reads a single :ref:`voltage_traces_npz_format` file as generated by the simrun package.

    Args:
        prefix (str): Path to the directory containing the simulation results.
        fname (str): Filename pointing to a voltage trace file. The file is expected to be in ``.npz`` format.

    See also:
        :py:meth:`~data_base.db_initializers.load_simrun_general.read_voltage_traces_from_file`
    """
    logger.warning(
        "You are loading voltage traces from npz files. This only works, if you are using a fixed stepsize of 0.025 ms"
    )
    data = np.load(os.path.join(prefix, fname))["arr_0"]
    data = np.transpose(data)
    vt = data[1:, :]
    t = np.array([0.025 * n for n in range(data.shape[1])])
    sim_trial_index_base = os.path.dirname(
        fname
    )  # os.path.dirname(os.path.relpath(prefix, fname))
    index = [
        str(os.path.join(sim_trial_index_base, str(index).zfill(6)))
        for index in range(len(vt))
    ]  ##this will be the sim_trial_index

    df = pd.DataFrame(vt, columns=t)
    df["sim_trial_index"] = index
    df.set_index("sim_trial_index", inplace=True)

    return df


def read_voltage_traces_by_filenames(prefix, fnames, divisions=None, repartition=None):
    """Reads a list of **multiple** voltage trace files and parses it to a dask dataframe.

    Also sets the database key ``sim_trial_index`` to contain the paths of the simulation trials.
    This is the default way of constructing a dask dataframe containing the voltage traces.

    Args:
        prefix (str): Path to the directory containing the simulation results.
        fnames (list): list of filenames pointing to voltage trace files
        divisions (list, optional): list of divisions for the dask dataframe. Default is ``None``, letting Dask handle it.
        repartition (bool|int): 
            If ``int``, the voltage trace dataframes will be partitioned to be of this length (approximately).
            If ``True``, the votlage trace dataframes will be partitioned to be of a default length: :py:attr:`~data_base.db_initializers.load_simrun_general.DEFAULT_VT_PARTITION_SIZE`
            If ``False``, the voltage trace dataframe will not be repartitioned, and the dask dataframe will be one ``.csv`` file per partition.

    Returns:
        dask.DataFrame: A dask dataframe containing the voltage traces.

    See also:
        :py:meth:`~data_base.db_initializers.load_simrun_general.read_voltage_traces_from_file`
        is used to read in each single voltage trace file. Consult this method for more information on how the data format
        is parsed.
    """
    assert repartition is not None
    fnames = sorted(fnames)
    meta = read_voltage_traces_from_file(prefix, fnames[0]).head(0)

    if repartition is not False:
        if divisions is not None:
            n_chunks = len(divisions) - 1
        else:
            if repartition == True: vt_partition_size = DEFAULT_VT_PARTITION_SIZE
            elif isinstance(repartition, int): vt_partition_size = repartition
            filelist = [os.path.join(prefix, fn) for fn in fnames]
            n_chunks = _estimate_n_chunks(filelist, partition_size=vt_partition_size)

        chunked_fnames = chunkIt(fnames, n_chunks)
        delayeds = [
            read_voltage_traces_from_files_pandas(prefix, fnames_chunk)
            for fnames_chunk in chunked_fnames
        ]
    else:
        # One file read per worker
        delayeds = [
            read_voltage_traces_from_file_delayed(prefix, fname, meta=meta) for fname in fnames
        ]
    
    if divisions is not None:
        assert len(divisions) - 1 == len(delayeds), "Expected n_delayeds = n_divisions + 1, but I have {} divisions and {} delayeds".format(
            len(divisions), len(delayeds)
        )

    ddf = dd.from_delayed(delayeds, meta=meta, divisions=divisions)
    return ddf

    
    
def load_dendritic_voltage_traces(
    db, 
    filelist,
    recsite_labels, 
    repartition=None,
    divisions=None,
    ):
    """Load the voltage traces from dendritic recording sites.

    This functions reads in all dendritic voltage trace files corresponding
    to each recsite label in :paramref:`suffix_key_dict`.
    Dendritic voltage traces recorded with recsites of the same label are aggregated in a single file.

    Attention:
        While voltage traces are combined depending on their recsite label, this does not mean
        that these voltage traces belong to the same simulation. Only the ``sim_trial_index`` is
        a reliable readout to check which simulation runs used the same parameters.

    Args:
        db (:py:class:`~data_base.DataBase`):
            The target database that should contain the parsed simulation results.
        suffix_key_dict (dict):
            Dictionary containing the suffixes of the dendritic voltage trace files.
            The keys are the labels of the recording sites, and the values are the suffixes of the dendritic voltage trace files.
        repartition (bool):
            If True, the dask dataframe is repartitioned to 5000 partitions (only if it contains over :math:`10000` entries).

    Returns:
        Dict[str, :py:class:`dask.dataframe.DataFrame`]: 
            Dictionary mapping each recsite label to a dask dataframe containing the associated voltage traces.

    """
    assert repartition is not None
    filelist = unique(filelist)
    df = pd.DataFrame({'filepath': filelist, 'label': recsite_labels})
    recsite_label_filelist_dict = df.groupby('label')['filepath'].apply(list).to_dict()
    recsite_dendvt_dict = {}
    for recsite_label, filelist in recsite_label_filelist_dict.items():
        ddf = read_voltage_traces_by_filenames(
            db["simresult_path"], filelist, divisions=divisions, repartition=repartition
        )
        recsite_dendvt_dict[recsite_label] = ddf
    return recsite_dendvt_dict


def _read_n_vtraces(fname):
    """Read the amount of voltage traces in a voltage trace file.
    
    Args:
        fname (str): Filename of a voltage trace file.
        
    Raises:
        NotImplementedError: If the voltage trace file is in .npz format.
        
    Returns:
        int: Amount of voltage traces in :paramref:`fname`.
    """
    if fname.endswith('.npz'):
        raise NotImplementedError("Don't know how to count the amount of traces for the .npz format: {}".format(fname))
    cols = pd.read_csv(
            fname, 
            nrows=0, 
            sep=r'\t', 
            engine="python", # use python engine to handle whitespace
            dtype=np.float64 # ensure all data is read as float64
        ).columns
    return len(cols) - 1  # one column is time, not voltage


def _estimate_average_vt_length(fnames, sample_size=1):
    """Estimate the length of all voltage traces in :paramref:`fnames`
    
    Reads the headers of :paramref:`sample_size` random files in :paramref:`fnames` to fetch
    how many voltage traces they contain. Returns the average amount.
    
    Args:
        fnames (List[str]): List of voltage trace filenames.
        sample_size (int): Amount of voltage traces headers to read in order to infer their length.
            Set to ``1`` if you expect all votlage trace filenames in :paramref:`fnames` to be of equal length.

    Returns:
        int: Estimated average length of all voltage trace files.
    """
    vt_lengths = [_read_n_vtraces(f) for f in np.random.choice(fnames, size=sample_size)]
    return int(np.mean(vt_lengths))

    
def _estimate_n_chunks(filelist, estimate_sample_size=1, partition_size=None):
    """Estimate how to divide filenames in chunks so that each chunk is approximately the target dask partition size.
    
    This function relies on the global config variable 
    :py:attr:`~data_base.db_initializers.load_simrun_general.config.DASK_TARGET_PARTITION_SIZE`

    Args:
        filelist (List[str]): List of voltage trace filenames
        estimate_sample_size (int, optional): 
            Amount of files to sample in order to estimate their length. Set to ``1`` if you expect all files to be of equal length.

    Returns:
        int: 
            The amount of chunks to divide the filelist in such that each chunk will yield a dataframe of approximate size 
            :py:attr:`~data_base.db_initializers.load_simrun_general.config.DASK_TARGET_PARTITION_SIZE`
    """
    assert partition_size is not None, "Please pass a target partition size."
    est_vt_length = _estimate_average_vt_length(filelist, sample_size=estimate_sample_size)
    n_files_per_chunk = partition_size // est_vt_length
    n_chunks = len(filelist) // n_files_per_chunk
    return n_chunks