[project]
authors = [{name = "Bjorge Meulemeester", email = "bjorge.meulemeester@mpinb.mpg.de"}]
dependencies = [
  "bluepyopt==1.9.126", 
  "sumatra==0.7.4", 
  "tables>=3.8.0,<4", 
  "redis>=5.2.0,<6", 
  "pyarrow==12.0.1", 
  "blosc>=1.11.1,<2", 
  "pandas-msgpack @ https://github.com/abast/pandas-msgpack.git"
]
description = "Add a short description here"
name = "in_silico_framework"
requires-python = ">=3.8, <3.10"
version = "0.1.0"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.system-requirements]
linux = "3.10"
libc = "2.17"

[tool.pixi.dependencies]
pandas = "1.1.3.*"
numpy = "1.19.2.*"
distributed = "2.30.0.*"
dask = "2.30.0.*"
flask = "1.1.4.*"
markupsafe = "2.0.1.*"
neuron = "7.8.2.*"
scikit-learn = "0.23.2.*"
simpleitk = ">=2.4.0,<3"
pypdf2 = ">=3.0.1,<4"
mock = ">=5.1.0,<6"
scandir = ">=1.10.0,<2"
jupyter = "==1.0.0"
kazoo = ">=2.10.0,<3"
scipy = "1.5.2.*"
matplotlib = ">=3.3.2,<4"
python = "3.8.*"
seaborn = ">=0.12.2,<0.13"
pyyaml = "==5.3.1"
plotly = ">=5.24.1,<6"
cython = ">=3.0.11,<4"
pytest = ">=8.3.3,<9"
pytest-xdist = ">=3.6.1,<4"
wheel = ">=0.45.1,<0.46"
dash = ">=2.18.1,<3"
pytest-cov = ">=5.0.0,<6"
fasteners = ">=0.17.3,<0.18"
jupyterlab = ">=3.5.3,<4"
ipywidgets = ">=8.1.5,<9"

[tool.pixi.pypi-options]
no-build-isolation = ["pandas-msgpack"]
