# Amira Project 201930
# AmiraZIBEdition
# Generated by AmiraZIBEdition 2020.11
remove -all
remove "grayScale.am" "physics.icol" "hocFileWithRad.hoc.am" "Spatial Graph View"

# Create viewers
viewer setVertical 0

viewer 0 setTransparencyType 5
viewer 0 setAutoRedraw 0
viewer 0 show
mainWindow show

_units setUnitsManagementMode 0

set hideNewModules 1
[ load ${AMIRA_ROOT}/data/colormaps/grayScale.am ] setLabel "grayScale.am"
"grayScale.am" setIconPosition 0 0
"grayScale.am" setNoRemoveAll 1
"grayScale.am" setVar "CustomHelp" {HxColormap256}
"grayScale.am" fire
"grayScale.am" setMinMax 0 255
"grayScale.am" flags setValue 1
"grayScale.am" shift setMinMax -1 1
"grayScale.am" shift setButtons 0
"grayScale.am" shift setEditButton 1
"grayScale.am" shift setIncrement 0.133333
"grayScale.am" shift setValue 0
"grayScale.am" shift setSubMinMax -1 1
"grayScale.am" scale setMinMax 0 1
"grayScale.am" scale setButtons 0
"grayScale.am" scale setEditButton 1
"grayScale.am" scale setIncrement 0.1
"grayScale.am" scale setValue 1
"grayScale.am" scale setSubMinMax 0 1
"grayScale.am" fire
"grayScale.am" setViewerMask 8191

set hideNewModules 1
[ load ${AMIRA_ROOT}/data/colormaps/physics.icol ] setLabel "physics.icol"
"physics.icol" setIconPosition 0 0
"physics.icol" setNoRemoveAll 1
"physics.icol" fire
"physics.icol" setMinMax 0 1
"physics.icol" flags setValue 1
"physics.icol" shift setMinMax -1 1
"physics.icol" shift setButtons 0
"physics.icol" shift setEditButton 1
"physics.icol" shift setIncrement 0.133333
"physics.icol" shift setValue 0
"physics.icol" shift setSubMinMax -1 1
"physics.icol" scale setMinMax 0 1
"physics.icol" scale setButtons 0
"physics.icol" scale setEditButton 1
"physics.icol" scale setIncrement 0.1
"physics.icol" scale setValue 1
"physics.icol" scale setSubMinMax 0 1
"physics.icol" fire
"physics.icol" setViewerMask 8191

set hideNewModules 0
[ load ${SCRIPTDIR}/hocFileWithRad.hoc.am ] setLabel "hocFileWithRad.hoc.am"
"hocFileWithRad.hoc.am" setIconPosition 20 10
"hocFileWithRad.hoc.am" fire
"hocFileWithRad.hoc.am" fire
"hocFileWithRad.hoc.am" setViewerMask 8191

set hideNewModules 0
create HxSpatialGraphView "Spatial Graph View"
"Spatial Graph View" setIconPosition 422 46
"Spatial Graph View" setVar "CustomHelp" {HxSpatialGraphView}
"Spatial Graph View" data connect "hocFileWithRad.hoc.am"
"Spatial Graph View" nodeColormap connect "physics.icol"
"Spatial Graph View" nodeColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View" nodeColormap setDefaultAlpha 0.500000
"Spatial Graph View" nodeColormap activateLocalRange 1
"Spatial Graph View" nodeColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View" nodeColormap enableAlpha 1
"Spatial Graph View" nodeColormap enableAlphaToggle 1
"Spatial Graph View" nodeColormap setAutoAdjustRangeMode 1
"Spatial Graph View" nodeColormap setColorbarMinMax 0 1
"Spatial Graph View" segmentColormap connect "physics.icol"
"Spatial Graph View" segmentColormap setDefaultColor 1 0.8 0.5
"Spatial Graph View" segmentColormap setDefaultAlpha 0.500000
"Spatial Graph View" segmentColormap activateLocalRange 1
"Spatial Graph View" segmentColormap setLocalMinMax 0.000000 1.000000
"Spatial Graph View" segmentColormap enableAlpha 1
"Spatial Graph View" segmentColormap enableAlphaToggle 1
"Spatial Graph View" segmentColormap setAutoAdjustRangeMode 1
"Spatial Graph View" segmentColormap setColorbarMinMax 0 1
"Spatial Graph View" fire
"Spatial Graph View" nodeOnOff setValue 0
"Spatial Graph View" nodeScale setIndex 0 0
"Spatial Graph View" fire
"Spatial Graph View" nodeScaleFactor setMinMax 0 1
"Spatial Graph View" nodeScaleFactor setButtons 0
"Spatial Graph View" nodeScaleFactor setEditButton 1
"Spatial Graph View" nodeScaleFactor setIncrement 0.1
"Spatial Graph View" nodeScaleFactor setValue 0.1
"Spatial Graph View" nodeScaleFactor setSubMinMax 0 1
"Spatial Graph View" nodeColoring setIndex 0 0
"Spatial Graph View" nodeLabelColoringOptions setValue 0
"Spatial Graph View" nodeColor setColor 0 0.8 0.8 0.8
"Spatial Graph View" segmentOnOff setValue 1
"Spatial Graph View" segmentStyle setValue 0 0
"Spatial Graph View" segmentStyle setToggleVisible 0 1
"Spatial Graph View" segmentStyle setValue 1 0
"Spatial Graph View" segmentStyle setToggleVisible 1 1
"Spatial Graph View" segmentStyle setValue 2 1
"Spatial Graph View" segmentStyle setToggleVisible 2 1
"Spatial Graph View" tubeScale setIndex 0 2
"Spatial Graph View" fire
"Spatial Graph View" tubeScaleFactor setMinMax 0 1
"Spatial Graph View" tubeScaleFactor setButtons 0
"Spatial Graph View" tubeScaleFactor setEditButton 1
"Spatial Graph View" tubeScaleFactor setIncrement 0.1
"Spatial Graph View" tubeScaleFactor setValue 0.0034286
"Spatial Graph View" tubeScaleFactor setSubMinMax 0 1
"Spatial Graph View" segmentWidth setMinMax 0 10
"Spatial Graph View" segmentWidth setButtons 0
"Spatial Graph View" segmentWidth setEditButton 1
"Spatial Graph View" segmentWidth setIncrement 0.666667
"Spatial Graph View" segmentWidth setValue 1
"Spatial Graph View" segmentWidth setSubMinMax 0 10
"Spatial Graph View" segmentColoring setIndex 0 0
"Spatial Graph View" segmentLabelColoringOptions setValue 0
"Spatial Graph View" segmentColor setColor 0 0.8 0.8 0.8
"Spatial Graph View" pointSize setMinMax 0 15
"Spatial Graph View" pointSize setButtons 0
"Spatial Graph View" pointSize setEditButton 1
"Spatial Graph View" pointSize setIncrement 1
"Spatial Graph View" pointSize setValue 4
"Spatial Graph View" pointSize setSubMinMax 0 15
"Spatial Graph View" setVisibility HIJMPLPPBPDPAAAAAOCOBPOB HIJMPLPPJPHEAAAAFNBNDDMN
"Spatial Graph View" fire
"Spatial Graph View" setViewerMask 8191
"Spatial Graph View" select
"Spatial Graph View" setPickable 1

set hideNewModules 0

viewer 0 setCameraOrientation 0.57735 0.57735 0.57735 2.0944
viewer 0 setCameraPosition -4089.13 -5428.88 407.72
viewer 0 setCameraFocalDistance 2459.23
viewer 0 setCameraNearDistance 6.15461
viewer 0 setCameraFarDistance 6166.93
viewer 0 setCameraType perspective
viewer 0 setCameraHeightAngle 44.9023
viewer 0 setAutoRedraw 1
viewer 0 redraw

correlationPanel closeTabs
correlationPanel setTabName 0 "Correlation 1"
correlationPanel 0 setLogScalingOnAxis 0 0
correlationPanel 0 setLogScalingOnAxis 1 0

histogramPanel closeTabs
histogramPanel setTabName 0 "Histogram 1"
histogramPanel 0 setLogScalingOnAxis 0 0
histogramPanel 0 setLogScalingOnAxis 1 1

theObjectPool setSelectionOrder {Spatial Graph View}
