# Builds ISF for any Python version (2.7/3.8/3.9), depending on the input
name: Build ISF
on:
  workflow_call:
    inputs:
      py_version:
        required: true
        type: string
jobs:
  build:
    runs-on: [ self-hosted, ibs3005 ]
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v3
      id: checkout
    - uses: xSAVIKx/artifact-exists-action@v0
      id: check_coverage_artifact
      with:
        name: isf${{ inputs.py_version }}
    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          all:
            - 'installer/**'
            - 'mechanisms/**'
            - 'tests/**'
            - '.github/**'

    - name: Build ISF
      # rebuild only if changes have been made, or the artifact is gone
      if: (steps.changes.outputs.all == 'true') || ! (steps.check_coverage_artifact.output.exists)
      run: |
        CONDA_TARGET_DIR="$(pwd)/anaconda_isf${{ inputs.py_version }}"
        if [ -d "$CONDA_TARGET_DIR" ]; then
          echo "Found existing installation in $(pwd). Removing previous Anaconda installation..."
          rm -r "$CONDA_TARGET_DIR"
        else
          echo "No previous Anaconda installation found. Continuing..."
        fi
        pushd .
        cd installer/py${{ inputs.py_version }}
        ./install.sh $CONDA_TARGET_DIR || exit 1
        popd
        source $CONDA_TARGET_DIR/bin/activate
        conda list
    - name: Save build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: isf${{ inputs.py_version }}
        path: anaconda_isf${{ inputs.py_version }}
