# This is a basic workflow to help you get started with Actions

name: Custom Conda Install

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #  branches: [ master ]
  # pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2

      # Install Anaconda2 and ISF dependencies (YAML)
      - name: Install Anaconda2
        run: |
          echo $HOME
          wget https://repo.anaconda.com/archive/Anaconda2-4.2.0-Linux-x86_64.sh --quiet
          bash Anaconda2-4.2.0-Linux-x86_64.sh -b -p ./anaconda2_isf
          source ./anaconda2_isf/bin/activate
          which conda
          conda update conda
          conda-env create --name isf-py27 --file etc/env-isf-py27.yml --quiet
          ##conda install --file etc/isf-py27-spec.txt --name root
          source activate isf-py27
          conda info
          conda list
          
          
