# This is a basic workflow to help you get started with Actions

name: Custom Conda Install

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #  branches: [ master ]
  # pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install Anaconda2 and update conda package manager
      - name: Install Anaconda2
        run: |
          wget https://repo.anaconda.com/archive/Anaconda2-4.2.0-Linux-x86_64.sh --quiet
          bash Anaconda2-4.2.0-Linux-x86_64.sh -b -p ~/conda2-isf
          source ~/conda2-isf/bin/activate
          which conda
          conda update conda

      # Updating the root environment. Install ISF dependencies (YAML)
      # NOTE: The environment file (yaml) is in the ISF repository 'etc' folder
      # REF: https://stackoverflow.com/questions/42352841/how-to-update-an-existing-conda-environment-with-a-yml-file
      - name: Install ISF dependencies
        run: |
          ## conda-env create --name isf-py27 --file etc/env-isf-py27.yml --quiet
          source ~/conda2-isf/bin/activate
          conda-env update --file etc/env-isf-py27.yml --prune
          conda info
          conda list
          
          
