name: Python Package using Conda

on: 
  # Trigger the workflow on push or pull request,
  # from the main and test-workflow branches.
  push:
    branches:
      - main
      - test-workflow
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install custom conda
    - uses: conda-incubator/setup-miniconda@v1
      with:
        installer-url: https://repo.anaconda.com/archive/Anaconda3-2020.02-Linux-x86_64.sh
        allow-softlinks: true
        show-channel-urls: true
        use-only-tar-bz2: true
    - shell: bash
      run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show


#    - name: Set up Python 2.7
#      uses: actions/setup-python@v2
#      with:
#        python-version: 2.7
#    - name: Add conda to system path
#      run: |
#        # $CONDA is an environment variable pointing to the root of the miniconda directory
#        echo $CONDA/bin >> $GITHUB_PATH
#    - name: Install dependencies
#      run: |
#        conda env update --file environment.yml --name base
#    - name: Test with unittest
#      run: |
#        python -m unittest discover
