# Installation of in-silico-framework followed by CI tests.
# Builds ISF locally on the MPINB-hosted runner and runs all tests
name: ISF Py3.8 (local) build/test
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: '*'
  # pull_request:
  #   branches: [ master ]  # It already automatically runs on push, no need for a second trigger
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ self-hosted, ibs3005 ]
    defaults:
      run:
        shell: bash -l {0}
    name: ISF Py3.8 (local) build/test
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Install Anaconda3 and update conda package manager
      - name: Download, install & build ISF for Python 3.8
        run: |
          CONDA_TARGET_DIR="$HOME/anaconda_isf3"
          if [ -d "$CONDA_TARGET_DIR" ]; then
            echo "Found existing installation in $HOME. Removing previous Anaconda installation..."
            rm -r "$CONDA_TARGET_DIR"
          else
            echo "No previous Anaconda installation found. Continuing..."
          fi
          pushd .
          cd installer/py3.8
          ./install.sh $CONDA_TARGET_DIR || exit 1
          popd
          source $CONDA_TARGET_DIR/bin/activate
          conda list
      # Run in-silico-framework tests
      - name: Test in-silico-framework
        run: |
          CONDA_TARGET_DIR="$HOME/anaconda_isf3"
          source $CONDA_TARGET_DIR/bin/activate;
          echo "Using Python: $(which python)"
          export PYTHONPATH=$CONDA_TARGET_DIR
          name=${{ runner.name }}
          runner_number=$( echo $name | grep -Eo '[0-9]+$' )
          port_number=${runner_number: -1}8786
          bokeh_port=${runner_number: -1}8787
          echo "Launching Dask server on $name"
          echo "Using port $port_number and bokeh port $bokeh_port" 
          dask-scheduler --port=$port_number --bokeh-port=$bokeh_port &
          dask-worker localhost:$port_number --nthreads 1 --nprocs 4 --memory-limit=100e15 &
          pytest -n 4 -rsx -vv --color=yes --cov-report xml:tests/coverage_reports/report_py3.xml --cov=. tests
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./tests/coverage_reports/report_py3.xml
          verbose: true # optional (default = false)
        
