# Installation of in-silico-framework followed by CI tests.
# Builds ISF locally on the MPINB-hosted runner and runs all tests
name: ISF Py2.7 (local) build/test
# Controls when the workflow will run
on:
  push: 
    branches: '*'
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    defaults:
      run:
        shell: bash -l {0}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install Anaconda2 and update conda package manager
      - name: Install Anaconda2
        run: |
          echo "Downloading Anaconda2-4.2.0-Linux-x86_64"
          wget https://repo.anaconda.com/archive/Anaconda2-4.2.0-Linux-x86_64.sh --quiet
          DIR="$HOME/conda2-isf"
          if [ -d "$DIR" ]; then
            echo "Found existing installation in $HOME. Removing previous Anaconda installation..."
            rm -r "$DIR"
          else
            echo "No previous Anaconda installation found. Continuing..."
          fi
          echo "Installing Anaconda2"
          bash Anaconda2-4.2.0-Linux-x86_64.sh -b -p ~/conda2-isf
          source ~/conda2-isf/bin/activate
          conda info
      # Updating the root environment. Install ISF dependencies (YAML)
      # NOTE: The environment file (yaml) is in the ISF repository 'installer' folder
      - name: Install ISF dependencies
        run: |
          source ~/conda2-isf/bin/activate
          echo "Installing 'in silico framework' dependencies in silent mode."
          conda-env create --name isf-py27 --file installer/env-isf-py27.yml --quiet
          source activate isf-py27
          conda list
          
      # Patch pandas library to support CategoricalIndex in msgpack format
      - name: Patch pandas library
        run: |
          echo "Patching pandas library."
          source ~/conda2-isf/bin/activate
          source activate isf-py27
          cd installer
          python patch_pandas_linux64.py
          conda list

      # Compile neuron mechanisms
      - name: Compile neuron mechanisms
        run: |
          echo "Compiling neuron mechanisms"
          source ~/conda2-isf/bin/activate
          source activate isf-py27
          pushd .
          cd mechanisms/channels_py2; nrnivmodl
          popd
          cd mechanisms/netcon_py2; nrnivmodl
          
      # Run in-silico-framework tests
      - name: Test in-silico-framework
        run: |
          source ~/conda2-isf/bin/activate
          source activate isf-py27
          export PYTHONPATH="$(pwd)"
          dask-scheduler --port=28786 --bokeh-port=28787 &
          dask-worker localhost:28786 --nthreads 1 --nprocs 4 --memory-limit=100e15 &
          python -m pytest -rsx -vv --color=yes tests/
