name: Linux
on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - .gitignore
      - 'CITATION.cff'
    branches:
      - develop
      - master
      - rc**
  push:
    branches:
      - master
      - docs-test-env
  workflow_dispatch:

jobs:
  test:
    name: Test linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install & setup environment
        uses: prefix-dev/setup-pixi@v0.8.8
        with:
          pixi-version: v0.53.0
          cache: true
          auth-host: prefix.dev
          auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
          manifest-path: pyproject.toml

      - name: Download barrel cortex model
        run: |
          echo ------------ Downloading barrel cortex model -------------
          pixi r download_bc_model

      - name: Preliminary setup
        run: |
          echo "------------ Preliminary setup for tests -------------"
          echo "Creating tests/logs/ directory..."
          mkdir -p ./tests/logs/

          unset DISPLAY
          if [ ! -d "$HOME/tmp" ]; then
            mkdir $HOME/tmp
          fi
          export TMPDIR=$HOME/tmp

          pixi r configure

      - name: Test ISF
        run: |
          echo "Starting test suite..."
          pixi r pytest -n 5 -rsx -vv --color=yes --durations=0 --cov-report xml:tests/logs/report_py38.xml --cov=. tests || exit 1
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DASK_CONFIG: tests/dask_config.yml

      - name: Save test logs
        uses: actions/upload-artifact@v4
        if: ${{ always() }} 
        with:
          name: ${{ github.run_id }}_logs
          path: |
            ./tests/logs/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./tests/logs/report_py38.xml
          verbose: true


