name: Py 3.8
on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - .gitignore
      - .github/**
  pull_request_target:
    types:
      - closed
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - .gitignore
      - .github/**
  push:
    branches:
      - testing
      - installer
  workflow_dispatch:

jobs:
  test:
    name: Test Py3.8-pixi
    runs-on: [ self-hosted, ibs3005 , py3.8 ]
    steps:
      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.8.0
        with:
          pixi-version: v0.39.0
          cache: true
          auth-host: prefix.dev
          auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}

      - name: Test in-silico-framework for Python 3.8 (pixi)
        run: |
          echo "------------ Preliminary setup for tests -------------"
          echo "Creating tests/logs/ directory..."
          mkdir -p ./tests/logs/
          if [ -f .coverage.${{ runner.name }}.* ]; then
            echo "Removing previous coverage files..."
            rm .coverage.${{ runner.name }}.*
          fi

          echo "------------ Setting up environment -------------"
          CONDA_TARGET_DIR="$HOME/anaconda_isf3.8"
          source $CONDA_TARGET_DIR/bin/activate
          echo "Using Python: $(which python)"
          export PYTHONPATH=$(pwd):$HOME
          echo $PYTHONPATH

          echo "------------ Configuring Dask -------------"
          name=${{ runner.name }}
          runner_number=$( echo $name | grep -Eo '[0-9]+$' )
          port_number=387${runner_number: -1}6
          bokeh_port=387${runner_number: -1}7
          echo "Killing all dask processes on ${{ runner.name }} for user $USER (if they exist)"
          pkill -U $USER dask-worker
          pkill -U $USER dask-scheduler
          echo "Killing all processes on ports $port_number and $bokeh_port"
          fuser -n tcp -k $port_number 
          fuser -n tcp -k $bokeh_port 
          echo "Launching Dask server on $name"
          echo "Using port $port_number and bokeh port $bokeh_port"

          export DASK_CONFIG=./config/dask_config.yml

          echo "------------ Running tests -------------"
          unset DISPLAY
          if [ ! -d "$HOME/tmp" ]; then
            mkdir $HOME/tmp
          fi
          export TMPDIR=$HOME/tmp
          (pixi run dask-scheduler --port=$port_number --bokeh-port=$bokeh_port --host=localhost --preload="import mechanisms, compatibility"> ./tests/logs/dask_scheduler_${{ github.run_id }}.log 2>&1) & \
          (pixi run dask-worker localhost:$port_number --nthreads 1 --nprocs 10 --memory-limit=100e15 --local-directory="." > ./tests/logs/dask_workers_${{ github.run_id }}.log 2>&1) & \
          pixi run pytest -n 5 -rsx -vv --color=yes --durations=15 --cov-report xml:tests/logs/report_py38.xml --cov=. --dask_server_port $port_number tests || exit 1;
          rm -rf $TMPDIR

      - name: Cleanup dask orphan processes
        if: ${{ always() }}
        run: |
          pkill -U $USER dask-scheduler
          pkill -U $USER dask-worker

      - name: Save test logs as artifacts
        uses: actions/upload-artifact@v3
        if: ${{ always() }} 
        with:
          name: ${{ github.run_id }}_logs
          path: |
            ./tests/logs/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./tests/logs/report_py38.xml
          verbose: true


