# Installation of in-silico-framework followed by CI tests.
# Builds ISF locally on the MPINB-hosted runner and runs all tests
name: ISF Py2.7 (local) build/test
# Controls when the workflow will run
on:
  push: 
    branches: '*'
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted
    defaults:
      run:
        shell: bash -l {0}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install Anaconda2 and update conda package manager
      - name: Install Anaconda2
        run: |
          CONDA_TARGET_DIR="$(pwd)/anaconda_isf2"
          if [ -d "$CONDA_TARGET_DIR" ]; then
            echo "Found existing installation in $HOME. Removing previous Anaconda installation..."
            rm -r "$CONDA_TARGET_DIR"
          else
            echo "No previous Anaconda installation found. Continuing..."
          fi
          pushd .
          cd installer/py2.7
          ./install.sh $CONDA_TARGET_DIR
          popd
          source $CONDA_TARGET_DIR/bin/activate
          conda list
      # Run in-silico-framework tests
      - name: Test in-silico-framework
        run: |
          CONDA_TARGET_DIR="$(pwd)/anaconda_isf2"
          source $CONDA_TARGET_DIR/bin/activate;
          echo "Using Python: $(which python)"
          export PYTHONPATH="$ISF_HOME"
          dask-scheduler --port=28786 --bokeh-port=28787 &
          dask-worker localhost:28786 --nthreads 1 --nprocs 4 --memory-limit=100e15 &
          python -m pytest -rsx -vv --color=yes tests/
