name: OSX
on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - .gitignore
    branches:
      - develop
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    name: Test pixi MacOS
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install & setup environment
        uses: prefix-dev/setup-pixi@v0.8.8
        with:
          pixi-version: v0.47.0
          cache: true
          auth-host: prefix.dev
          auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
          manifest-path: pyproject.toml
      - name: Preliminary setup
        run: |
          echo "------------ Preliminary setup for tests -------------"
          echo "Creating tests/logs/ directory..."
          mkdir -p ./tests/logs/

          echo "------------ Configuring Dask -------------"
          port_number=38786
          bokeh_port=38787
          echo "Launching Dask server"
          echo "Using port $port_number and bokeh port $bokeh_port"
          export DASK_CONFIG=./config/dask_config.yml

          unset DISPLAY
          if [ ! -d "$HOME/tmp" ]; then
            mkdir $HOME/tmp
          fi
          export TMPDIR=$HOME/tmp

      - name: Test ISF
        run: |
          (\
            pixi r dask-scheduler \
            --port=8786 \
            --dashboard-address=8787 \
            --host=localhost \
            > dask_scheduler_out_${{ github.run_id }}.log \
            2> dask_scheduler_err_${{ github.run_id }}.log & \
          ) &
          sleep 5

          (\
            pixi r dask-worker localhost:8786 \
            --nthreads=1 \
            --nprocs=5 \
            --memory-limit=100e15 \
            --dashboard-address=8787 \
            > dask_worker_out_${{ github.run_id }}.log \
            2> dask_worker_err_${{ github.run_id }}.log & \
          ) &
          
          echo "Launching test suite..."
          pixi r pytest -n 5 -rsx -vv --color=yes --durations=15 --cov-report xml:tests/logs/report_py38.xml --cov=. --dask_server_port 8786 tests || exit 1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Test ModelDataBase backwards compatibility
        run: |
          export ISF_USE_MDB=1
          pixi r pytest -n 5 -rsx -vv --color=yes --durations=15 --dask_server_port 8786 tests/test_data_base/
          unset ISF_USE_MDB
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Teardown
        run: |
          echo "------------ Teardown -------------"
          echo "Killing Dask server"
          pkill -f dask-scheduler
          pkill -f dask-worker

      - name: Save test logs
        uses: actions/upload-artifact@v4
        if: ${{ always() }} 
        with:
          name: ${{ github.run_id }}_logs
          path: |
            ./tests/logs/