name: Windows
on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - README.md
      - CHANGELOG.md
      - .gitignore
    branches:
      - develop
      - master
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    name: Test pixi windows
    runs-on: ['self-hosted', 'Windows']

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install & setup environment
        uses: prefix-dev/setup-pixi@v0.8.8
        with:
          pixi-version: v0.47.0
          cache: true
          auth-host: prefix.dev
          auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
          manifest-path: pyproject.toml
          post-cleanup: true
          pixi-bin-path: ${{ runner.temp }}\Scripts\pixi.exe

      - name: Preliminary setup
        run: |
            Write-Host "------------ Preliminary setup for tests -------------"
            Write-Host "Creating tests/logs/ directory..."
            New-Item -ItemType Directory -Force -Path ./tests/logs/

            Write-Host "------------ Configuring Dask -------------"
            $env:DASK_CONFIG = "./config/dask_config.yml"

            Remove-Item Env:DISPLAY -ErrorAction SilentlyContinue
            if (-Not (Test-Path "$HOME/tmp")) {
            New-Item -ItemType Directory -Path "$HOME/tmp"
            }
            $env:TMPDIR = "$HOME/tmp"

      - name: Test ISF
        run: |
          Start-Process pixi -ArgumentList "r dask-scheduler --port=8786 --dashboard-address=8787 --host=localhost"`
             -RedirectStandardOutput "./tests/dask_scheduler_out_${{ github.run_id }}.log" `
             -RedirectStandardError "./tests/dask_scheduler_err_${{ github.run_id }}.log" `

          Start-Process pixi -ArgumentList "r dask-worker localhost:8786 --nthreads=2 --nprocs=4 --memory-limit=4GB --dashboard-address=8787"
             -RedirectStandardOutput "./tests/dask_worker_out_${{ github.run_id }}.log" `
             -RedirectStandardError "./tests/dask_worker_err_${{ github.run_id }}.log" `

          Write-Host "------------ Running tests -------------"
          pixi r pytest `
            -n 5 `
            -rsx `
            -vv `
            --color=yes `
            --durations=15 `
            --cov-report xml:tests\logs\report_py38.xml `
            --cov=. `
            --dask_server_port 8786 tests
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEURONHOME: C:\nrn

      - name: Test ModelDataBase backwards compatibility
        run: |
          $env:ISF_USE_MDB = "1"
          pixi r pytest -rsx -vv --color=yes --durations=15 --dask_server_port 8786 tests\test_data_base\
          Remove-Item Env:ISF_USE_MDB -ErrorAction SilentlyContinue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEURONHOME: C:\nrn

      - name: Save test logs
        uses: actions/upload-artifact@v4
        if: ${{ always() }} 
        with:
          name: ${{ github.run_id }}_logs
          path: |
            ./tests/logs/